# Generated by Django 5.2.5 on 2025-08-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyzox', '0002_product_related_products_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
